config/routes.rb
Rails.application.routes.draw do

	
  devise_for :users

  
  get '/users/:id', to: 'users#show', as: 'user'


  root 'home#index'


  resources :order, only: [:new, :show, :index]
  post 'order/create', to: 'order#create', as: 'order_creation'

  
  resources :item 

  get '/category/:id', to: "category#show", as: 'show_category'
   
  post 'cart_item', to: "cart_item#create"
  delete 'cart_item.:id', to: "cart_item#destroy"
  post 'cart_item/:id/add' => "cart_item#add_quantity", as: "cart_item_add"
  post 'cart_item/:id/reduce' => "cart_item#reduce_quantity", as: "cart_item_reduce"



resources :adminpage
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :items, through: :cart_items
  belongs_to :user
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :cart
  belongs_to :order, optional: true 
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
end

app/models/item.rb
require 'open-uri'
class Item < ApplicationRecord
  validates :price, presence: true, numericality: {greater_than: 0}, on: :create
  validates :title, presence: true, format: {with: /\A[a-zA-Z0-9+\s]+\z/, message: "Only alpha-numeric characters"}, length: { in: 3..30 }, on: :create
  validates :description, presence: true, length: {in: 10..500, message: "Between 10 and 500 characters"}, on: :create

  has_one_attached :image
  has_many :cart_items, dependent: :destroy
  belongs_to :category
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :cart
  has_many :orders
end

app/controllers/adminpage_controller.rb
class AdminpageController < ApplicationController
  def new

  end

  def index
    unless current_user.admin?
      redirect_to root_path
    end
  		@user = current_user
  		@items = Item.all
  		@orders = Order.all
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  before_action :current_cart


   def show
     @cart = @current_cart
   end

   def destroy
     @cart = @current_cart
     @cart.destroy
     session[:cart_id] = nil
     redirect_to root_path
   end


   private
   def current_cart
     if session[:cart_id]
       cart = Cart.find_by(id: session[:cart_id])
       if cart.present?
         @current_cart = cart
       else
         session[:cart_id] = nil
       end
     end


      if session[:cart_id] == nil && current_user
       @current_cart = Cart.create(user_id: current_user.id)
       session[:cart_id] = @current_cart.id
     end

     
   end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController

  def show
    @items = Item.where(category_id: params[:id].to_i)
  end 

end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  def index
    @current_cart 
  end
end

app/controllers/item_controller.rb
class ItemController < ApplicationController



  def new
  	@item = Item.new
  end

  def index
    @items = Item.all
  end

  def edit
  	 @item = Item.find(params[:id])
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.create!(item_params)
    redirect_to root_path
  end

  def update
  	@item = Item.find(params[:id])
  	@item.update(item_params)
  end

  def destroy
  	Item.destroy(params[:id])
  end

  private

  def item_params
  	params.require(:item).permit(:image, :title, :description, :price)
  end
end

app/controllers/order_controller.rb
include CartTotal

class OrderController < ApplicationController
  def new
  end

  def create
    @amount = ((total(session[:cart_id]).to_i) * 100)
    @order = Order.new

    @order.total = total(session[:cart_id]).to_i 
    @order.cart_items = @current_cart.cart_items
    @order.user_id = @current_cart.user_id
    @order.save
    redirect_to order_creation_path

    Cart.destroy(session[:cart_id])
    session[:cart_id] = nil
    @current_cart = Cart.create(user_id: current_user.id)
    session[:cart_id] = @current_cart.id

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer => customer.id,
      :amount => @amount,
      :description => 'Paiement de #{current_user}',
      :currency => 'eur'
    )
    UserMailer.order_email(current_user, @order).deliver_now
    AdminMailer.user_order_email(current_user, @order).deliver_now
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to root_path
  end

  def show
    @order = Order.last

  end

  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
	  @user = User.find(params[:id])
	end
end

app/helpers/adminpage_helper.rb
module AdminpageHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def total
    sum = 0
    Cart.find(session[:cart_id]).cart_items.each do |x|
      sum += x.quantity * x.item.price
    end
  return sum 
  end 

  def total_stripe
    sum = 0
    Cart.find(session[:cart_id]).cart_items.each do |x|
      sum += x.quantity * x.item.price
    end
  return sum * 100
  end
  def total_quantity
    q = 0
    Cart.find(session[:cart_id]).cart_items.each do |x|
      q += x.quantity
    end
    return q
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/cart_item_helper.rb
module CartItemHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/category/show.html.erb
<%= render "shared/index_items" %>

app/views/item/_form.html.erb
<%= form_with model: @item do |f| %>

<div class="form-group">
   	<%= f.label :Image %>:
    <%= f.file_field :image %><br/>
</div>



<div class="form-group">
   	<%= f.label :Title %>:
    <%= f.text_field :title, :class => "form-control" %><br/>
</div>



<div class="form-group">
   	<%= f.label :Description %>:
    <%= f.text_field :description, :class => "form-control" %><br/>
</div>


<div class="form-group">
   	<%= f.label :Price %>:
    <%= f.text_field :price, :class => "form-control" %><br/>
</div>
  
	<%= f.submit :class => "btn btn-primary" %>

<% end %>

app/views/item/destroy.js.erb
$('.product-remove').bind('ajax:success', function(){
   $(this).closest('div').fadeOut();
});

app/views/item/edit.html.erb
<h1>Item : <%= @item.title%></h1>
<%= render "form", item: @item %>

app/views/item/index.html.erb
    <!-- ##### Breadcumb Area Start ##### -->
    <div class="breadcumb_area bg-img">
        <div class="container h-100">
            <div class="row h-100 align-items-center">
                <div class="col-12">
                    <div class="page-title text-center">
                        <h2>Shop</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Breadcumb Area End ##### -->

    <!-- ##### Shop Grid Area Start ##### -->
    <section class="shop_grid_area section-padding-80">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-4 col-lg-3">
                    <div class="shop_sidebar_area">

                        <!-- ##### Single Widget ##### -->
                        <div class="widget catagory mb-50">
                            <!-- Widget Title -->
                            <h6 class="widget-title mb-30">Catégories</h6>

                            <!--  Catagories  -->
                            <div class="catagories-menu">
                                <ul id="menu-content2" class="menu-content collapse show">
                                    <!-- Single Item -->
                                    <li data-toggle="collapse" data-target="#clothing">
                                        <a href="#">Chat1</a>
                                    </li>
                                    <!-- Single Item -->
                                    <li data-toggle="collapse" data-target="#shoes" class="collapsed">
                                        <a href="#">Chat2</a>
                                    </li>
                                    <!-- Single Item -->
                                    <li data-toggle="collapse" data-target="#accessories" class="collapsed">
                                        <a href="#">Chat3</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        
                    </div>
                </div>

                <div class="col-12 col-md-8 col-lg-9">
                    <div class="shop_grid_product_area">
                        <div class="row">
                            <div class="col-12">
                                <div class="product-topbar d-flex align-items-center justify-content-between">
                                    <!-- Total Products -->
                                    <div class="total-products">
                                        <p><span><%= Item.count %></span> products found</p>
                                    </div>
                                    <!-- Sorting -->
                                    <div class="product-sorting d-flex">
                                        <p>Sort by:</p>
                                        <form action="#" method="get">
                                            <select name="select" id="sortByselect">
                                                <option value="value">Highest Rated</option>
                                                <option value="value">Newest</option>
                                                <option value="value">Price: $$ - $</option>
                                                <option value="value">Price: $ - $$</option>
                                            </select>
                                            <input type="submit" class="d-none" value="">
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">



                            <!-- Single Product -->
                            <% Item.all.each do |item| %>
                            <div class="col-12 col-sm-6 col-lg-4">
                                
                                <div class="single-product-wrapper">
                                    <!-- Product Image -->
                                    <div class="product-img">
                                       <% unless item.image.attachment.nil? %>
                                       <%= image_tag item.image %>
                                       <% else %>
                                       <img src="<%= item.image_url %>" alt="img shop">
                                       <!-- Favourite -->
                                       <div class="product-favourite">
                                           <a href="#" class="favme fa fa-heart"></a>
                                       </div>
                                       <% end %>
                                    </div>
                                    

                                    <!-- Product Description -->
                                    <div class="product-description">
                                        

                                           
                                            <h6><%= link_to item.title, item_path(item.id) %></h6>
                                       
                                        <p class="product-price"><%=number_to_currency( item.price, :unit=>'€') %></p>

                                        <!-- Hover Content -->
                                        <div class="hover-content">
                                            <!-- Add to Cart -->
                                            <div class="add-to-cart-btn">                                                  
                                                 <%= link_to "Add to cart", cart_item_path(item_id: item.id), method: :post, class: "btn essence-btn", remote: true %>
                                            </div>
                                        </div>

                                    </div>

                                </div>
                                
                            </div>
                            <% end %>
                            <!-- Single Product -->

                        </div>
                    </div>

                    
                </div>
            </div>
        </div>
    </section>

app/views/item/new.html.erb
<%= form_for @item, url: {action: "create"} do |f|%>

<div class="form-group">
   	<%= f.label :Image %>:
    <%= f.file_field :image %><br/>
</div>



<div class="form-group">
   	<%= f.label :Title %>:
    <%= f.text_field :title, :class => "form-control" %><br/>
</div>



<div class="form-group">
   	<%= f.label :Description %>:
    <%= f.text_field :description, :class => "form-control" %><br/>
</div>


<div class="form-group">
   	<%= f.label :Price %>:
    <%= f.text_field :price, :class => "form-control" %><br/>
</div>
  
	<%= f.submit "create", :class => "btn btn-primary" %>

<% end %>

app/views/item/show.html.erb
<!-- ##### Single Product Details Area Start ##### -->
    <section class="single_product_details_area d-flex align-items-center">

        <!-- Single Product Thumb -->
        <div class="single_product_thumb clearfix mt-3 mb-3">
            <div class="product-img">
               
               <% unless @item.image.attachment.nil? %>
               <%= image_tag @item.image %>
               <% else %>
               <img src="<%= @item.image_url %>" alt="img shop" class="ml-4">
               <% end %>
            </div>
        </div>

        <!-- Single Product Description -->
        <div class="single_product_desc clearfix">
            
            <a href="#">
                <h2><%= @item.title %></h2>
            </a>
            <p class="product-price"><%= number_to_currency( @item.price, :unit=>'€') %></p>
            <p class="product-desc"><%= @item.description %></p>

            <!-- Form -->
            <form class="cart-form clearfix" method="post">
                <!-- Select Box -->
                <div class="select-box d-flex mt-50 mb-30">
                    <select name="select" id="productSize" class="mr-5">
                        <option value="value">JPG</option>
                        <option value="value">TIFF</option>
                        <option value="value">PNG</option>
                    </select>
                   
                </div>
                <!-- Cart & Favourite Box -->
                <div class="cart-fav-box d-flex align-items-center">
                    <!-- Cart -->
                    <% if user_signed_in? %>
                    <%= link_to "Add to cart", cart_item_path(item_id: @item), method: :post, class: "btn essence-btn" %>
                    <% end %>
                    <!-- Favourite -->
                    <div class="product-favourite ml-4">
                        <a href="#" class="favme fa fa-heart"></a>
                    </div>
                </div>
            </form>
        </div>
    </section>

app/views/order/show.html.erb
<!-- ##### Breadcumb Area Start ##### -->
    <div class="breadcumb_area bg-img">
        <div class="container h-100">
            <div class="row h-100 align-items-center">
                <div class="col-12">
                        <h2>Checkout</h2>
                    
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Breadcumb Area End ##### -->

    <!-- ##### Checkout Area Start ##### -->
    <div class="container">
    <div class="checkout_area section-padding-30">
        
            

                
                    <div class="checkout_details_area mt-50 clearfix">

                        
                            <h5 class="mb-30">Your order</h5>
									
                                <div class="col-12 col-sm-6 col-lg-4 mb-3">
                                	<% @order.cart_items.each do |order| %>
                                	<div class="product-img">
                                       <% unless order.item.image.attachment.nil? %>
                                       <%= image_tag order.item.image %>
                                       <% else %>
                                       <img src="<%= order.item.image_url %>" alt="img shop">                   
                                       <% end %>
                                    </div>
                                	  <h2>
                                	    <%= order.item.title %>
                                	  </h2>
                                	  <p class="product-desc">
                                	    <%= order.item.description %>
                                	  </p>
                                	  <p class="product-price">
                                	  	Qt : <%= order.quantity %>                         		
                                	  </p>
                                	  
                                	  <p class="product-price">
                                	  	<strong>
                                	    <%= number_to_currency( order.item.price * order.quantity, :unit=>'€') %>
                                	    </strong>
                                	  </p>
                                	  
                                <% end %> 
								

                    			</div>
                    <%= link_to "Back to home", :back, class: "btn essence-btn mt-3 mb-50" %> 	 
               		</div>
		
           
            
        
    </div>
	</div>
    <!-- ##### Checkout Area End ##### -->

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<div class="container mt-100 mb-100">
	<div class="row">
		<div class="col-lg-6 col-sm-12">

		<h3 class="mt-5">Bonjour, <%= @user.email %></h3>
		<%= link_to "Edit profile", edit_user_registration_path(current_user.id), class: "btn essence-btn mt-3" %>
		</div>
			<div class="container">
				<h5 class="mt-5 mb-4">Your last orders</h5>
				
				<table class="table mb-100">
					<% i = 0 %>
					<% @user.orders.each do |o|  %>

					<% if o.cart_items.count != 0 %>
				  <thead>
				    <tr>
				      <th scope="col">Order <%= i += 1 %></th>
				      <th scope="col">Item</th>
				      <th scope="col">Quantity</th>
				      <th scope="col">Price</th>
				    </tr>
				  </thead>
				  <tbody>
				  	<% o.cart_items.each do |order| %>
				    <tr>
				      <th scope="row"></th>
				      <td><%= order.item.title %></td>
				      <td><%= order.quantity %> </td>
				      <td><%= number_to_currency( order.item.price * order.quantity, :unit=>'€') %></td>
				    </tr>
				    <% end %>
				  </tbody>
				  <% end %>
				  <% end %>
				</table>
			
			<%= link_to "Shop", item_index_path, class: "btn essence-btn mt-3" %>
			</div>

		
	</div>
</div>