config/routes.rb
Rails.application.routes.draw do

	
  devise_for :users

  
  get '/users/:id', to: 'users#show', as: 'user'


  root 'home#index'


  resources :order, only: [:new, :show, :index]
  post 'order/create', to: 'order#create', as: 'order_creation'

  
  resources :item 

  get '/category/:id', to: "category#show", as: 'show_category'
   
  post 'cart_item', to: "cart_item#create"
  delete 'cart_item.:id', to: "cart_item#destroy"
  post 'cart_item/:id/add' => "cart_item#add_quantity", as: "cart_item_add"
  post 'cart_item/:id/reduce' => "cart_item#reduce_quantity", as: "cart_item_reduce"



resources :adminpage
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :items, through: :cart_items
  belongs_to :user
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :cart
  belongs_to :order, optional: true 
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
end

app/models/item.rb
require 'open-uri'
class Item < ApplicationRecord
  validates :price, presence: true, numericality: {greater_than: 0}, on: :create
  validates :title, presence: true, format: {with: /\A[a-zA-Z0-9+\s]+\z/, message: "Only alpha-numeric characters"}, length: { in: 3..30 }, on: :create
  validates :description, presence: true, length: {in: 10..500, message: "Between 10 and 500 characters"}, on: :create

  has_one_attached :image
  has_many :cart_items, dependent: :destroy
  belongs_to :category
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :cart
  has_many :orders
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  before_action :current_cart


   def show
     @cart = @current_cart
   end

   def destroy
     @cart = @current_cart
     @cart.destroy
     session[:cart_id] = nil
     redirect_to root_path
   end


   private
   def current_cart
     if session[:cart_id]
       cart = Cart.find_by(id: session[:cart_id])
       if cart.present?
         @current_cart = cart
       else
         session[:cart_id] = nil
       end
     end


      if session[:cart_id] == nil && current_user
       @current_cart = Cart.create(user_id: current_user.id)
       session[:cart_id] = @current_cart.id
     end

     
   end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  def index
    @current_cart 
  end
end

app/controllers/item_controller.rb
class ItemController < ApplicationController



  def new
  	@item = Item.new
  end

  def index
    @items = Item.all
  end

  def edit
  	 @item = Item.find(params[:id])
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.create!(item_params)
    redirect_to root_path
  end

  def update
  	@item = Item.find(params[:id])
  	@item.update(item_params)
  end

  def destroy
  	Item.destroy(params[:id])
  end

  private

  def item_params
  	params.require(:item).permit(:image, :title, :description, :price)
  end
end

app/controllers/order_controller.rb
include CartTotal

class OrderController < ApplicationController
  def new
  end

  def create
    @amount = ((total(session[:cart_id]).to_i) * 100)
    @order = Order.new

    @order.total = total(session[:cart_id]).to_i 
    @order.cart_items = @current_cart.cart_items
    @order.user_id = @current_cart.user_id
    @order.save
    redirect_to order_creation_path

    Cart.destroy(session[:cart_id])
    session[:cart_id] = nil
    @current_cart = Cart.create(user_id: current_user.id)
    session[:cart_id] = @current_cart.id

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer => customer.id,
      :amount => @amount,
      :description => 'Paiement de #{current_user}',
      :currency => 'eur'
    )
    UserMailer.order_email(current_user, @order).deliver_now
    AdminMailer.user_order_email(current_user, @order).deliver_now
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to root_path
  end

  def show
    @order = Order.last

  end

  def index
  end

end

app/helpers/adminpage_helper.rb
module AdminpageHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def total
    sum = 0
    Cart.find(session[:cart_id]).cart_items.each do |x|
      sum += x.quantity * x.item.price
    end
  return sum 
  end 

  def total_stripe
    sum = 0
    Cart.find(session[:cart_id]).cart_items.each do |x|
      sum += x.quantity * x.item.price
    end
  return sum * 100
  end
  def total_quantity
    q = 0
    Cart.find(session[:cart_id]).cart_items.each do |x|
      q += x.quantity
    end
    return q
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/cart_item_helper.rb
module CartItemHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>THPKittens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
  
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <%= render"shared/header" %>
    <%= render"shared/basket" %>
    


    <%= yield %>

    <%= render"shared/footer" %>
    <%= javascript_include_tag 'application'%>
  </body>
</html>

app/views/shared/_basket.html.erb
<!-- ##### Right Side Cart Area ##### -->
<div class="cart-bg-overlay"></div>

<div class="right-side-cart-area">

  <!-- Cart Button -->

  <% if current_user %>
  <div class="cart-button">
    <a href="#" id="rightSideCart">
      <%= image_tag("core-img/bag.svg", alt: "basket") %> <span>
        <%= total_quantity %> </span></a>
  </div>
  <% end %>

  <div class="cart-content d-flex">

    <!-- Cart List Area -->
    <div class="cart-list">

      <!-- Single Cart Item -->
      <% if session[:cart_id] %>
      <% @current_cart.cart_items.each do |x| %>

      <div class="single-cart-item ml-20">
        <a href="<%= item_path(x.item_id) %>" class="product-image mb-2">
          <% unless x.item.image.attachment.nil? %>
          <%= image_tag x.item.image %>
          <% else %>
          <img src="<%= x.item.image_url %>" alt="img shop">
          <% end %>
          <!-- Cart Item Desc -->
          <div class="cart-item-desc">
            <h6>
              <%= x.item.title  %>
            </h6>

          </div>
        </a>
      </div>
      <span><strong>
          <%= number_to_currency( x.item.price, :unit=>'€') %></strong></span>



      <span class="hp ml-1">
        <%= link_to image_tag('core-img/arrow-up.svg'), cart_item_add_path(x.id), method: :post  %></span>
      <span class="hp">
        <%= link_to image_tag('core-img/arrow-down.svg'), cart_item_reduce_path(x.id), method: :post  %></span>
      <span class="badge badge-dark ml-1">Qt :
        <%= x.quantity %></span>
      <span class="badge badge-danger hp mb-2">
        <%= link_to 'Destroy', cart_item_path(x.id), method: :delete %></span>

      <% end %>
      <% end %>
    </div>


    <!-- Cart Summary -->
    <% if user_signed_in? %>
    <div class="cart-amount-summary">

      <h2>Summary</h2>
      <ul class="summary-table">

        <li><span>delivery:</span> <span>Free</span></li>
        <li><span>total:</span> <span>
            <%= total %> €</span></li>

      </ul>

      <%= form_tag order_creation_path do %>

      <article>
        <% if flash[:error].present? %>
        <div id="error_explanation">
          <p>
            <%= flash[:error] %>
          </p>
        </div>
        <% end %>

      </article>

      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-key="<%= Rails.configuration.stripe[:publishable_key] %>" data-description="Le prix de votre panier" data-amount="<%= total_stripe %>" data-currency="eur" data-locale="auto"></script>
      <% end %>
      <% else %>

      <%= link_to('Sign in', new_user_session_path)  %>



      <% end %>


    </div>
  </div>
</div>
<!-- ##### Right Side Cart End ##### -->

app/views/shared/_basket_partial.html.erb
   
        <!-- Cart Button -->
       
        <% if current_user %>
       <div class="cart-button">
           <a href="#" id="rightSideCart"><%= image_tag("core-img/bag.svg", alt: "basket") %> <span><%= @current_cart.items.count %> </span></a>
       </div>
        <% end %>
        
       <div class="cart-content d-flex">

           <!-- Cart List Area -->
           <div class="cart-list">

               <!-- Single Cart Item -->
               <% if session[:cart_id] %>
               <% @current_cart.cart_items.each do |x| %>

               <div class="single-cart-item ml-20">
                   <a href="<%= item_path(x.item_id) %>" class="product-image">
                        <img src="<%= x.item.image_url %>" alt="img shop">
                       <!-- Cart Item Desc -->
                       <div class="cart-item-desc">
                         <h6><%= x.item.title  %></h6>
         
                       </div>
                   </a>
               </div>
               <span><strong><%= number_to_currency( x.item.price, :unit=>'€') %></strong></span>

               

               <span class="hp ml-1"><%= link_to image_tag('core-img/arrow-up.svg'), cart_item_add_path(x.id), method: :post  %></span>
               <span class="hp"><%= link_to image_tag('core-img/arrow-down.svg'), cart_item_reduce_path(x.id), method: :post  %></span>
               <span class="badge badge-dark ml-1">Qt : <%= x.quantity %></span>
               <span class="badge badge-danger hp"><%= link_to 'Destroy', cart_item_path(x.id), method: :delete %></span>
               
               <% end %>
               <% end %>
           </div>
           

           <!-- Cart Summary -->
           <% if user_signed_in? %>
           <div class="cart-amount-summary">

               <h2>Summary</h2>
               <ul class="summary-table">

                   <li><span>delivery:</span> <span>Free</span></li>
                   <li><span>total:</span> <span><%= total %> €</span></li>

               </ul>
               
               <%= form_tag order_creation_path do %>

                 <article>
                   <% if flash[:error].present? %>
                     <div id="error_explanation">
                       <p><%= flash[:error] %></p>
                     </div>
                   <% end %>
                   
                 </article>
                 
                 <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                         data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                         data-description="Le prix de votre panier"
                         data-amount="<%= total_stripe %>"
                         data-currency="eur"
                         data-locale="auto"></script>
               <% end %>
               <% else %>

               <%= link_to('Sign in', new_user_session_path)  %>  


               
               <% end %>


           </div>
       </div>

app/views/shared/_footer.html.erb
 <!-- ##### Footer Area Start ##### -->
    <footer class="footer_area clearfix">
        <div class="container">
            <div class="row">
                <!-- Single Widget Area -->
                <div class="col-12 col-md-6">
                    <div class="single_widget_area d-flex mb-30">
                        <!-- Logo -->
                        <a class="nav-brand" href="/"><h5>🐈</h5></a>
                        <!-- Footer Menu -->
                        <div class="footer_menu">
                            <ul>
                            <li><a href="/">Home</a></li>
                            <li><a href="/item">Shop</a></li>
                            
                            

                            <% if user_signed_in? %>
                              <li>
                              <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
                              </li>
                            <% else %>
                              <li>
                              <%= link_to('Sign in', new_user_session_path)  %>  
                              </li>
                              <li>
                                <%= link_to('Sign up', new_user_registration_path)  %>
                              </li>
                            <% end %>
                        </ul>
                        </div>
                    </div>
                </div>
                <!-- Single Widget Area -->
                <div class="col-12 col-md-6">
                    <div class="single_widget_area mb-30">
                        <ul class="footer_widget_menu">
                            <li><a href="#">Order Status</a></li>
                            <li><a href="#">Payment Options</a></li>
                            <li><a href="#">Shipping and Delivery</a></li>
                            <li><a href="#">Guides</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                            <li><a href="#">Terms of Use</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="row align-items-end">
                <!-- Single Widget Area -->
                <div class="col-12 col-md-6">
                    <div class="single_widget_area">
                        <div class="footer_heading mb-30">
                            <h6>Subscribe</h6>
                        </div>
                        <div class="subscribtion_form">
                            <form action="#" method="post">
                                <input type="email" name="mail" class="mail" placeholder="Your email here">
                                <button type="submit" class="submit"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></button>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- Single Widget Area -->
                <div class="col-12 col-md-6">
                    <div class="single_widget_area">
                        <div class="footer_social_area">
                            <a href="#" data-toggle="tooltip" data-placement="top" title="Facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                            <a href="#" data-toggle="tooltip" data-placement="top" title="Instagram"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                            <a href="#" data-toggle="tooltip" data-placement="top" title="Twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                            <a href="#" data-toggle="tooltip" data-placement="top" title="Pinterest"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                            <a href="#" data-toggle="tooltip" data-placement="top" title="Youtube"><i class="fa fa-youtube-play" aria-hidden="true"></i></a>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </footer>

app/views/shared/_header.html.erb
 <header class="header_area">
        <div class="classy-nav-container breakpoint-off d-flex align-items-center justify-content-between">
            <!-- Classy Menu -->
            <nav class="classy-navbar" id="essenceNav">
                <!-- Logo -->
                <a class="nav-brand" href="/"><h2>🐈</h2></a>
                <!-- Navbar Toggler -->
                <div class="classy-navbar-toggler">
                    <span class="navbarToggler"><span></span><span></span><span></span></span>
                </div>
                <!-- Menu -->
                <div class="classy-menu">
                    <!-- close btn -->
                    <div class="classycloseIcon">
                        <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                    </div>
                    <!-- Nav Start -->
                    <div class="classynav">
                        <ul>
                            <li><a href="/">Home</a></li>
                            <li><a href="/item">Shop</a></li>
                            
                            

                            <% if user_signed_in? %>
                              <li>
                              <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
                              </li>
                            <% else %>
                              <li>
                              <%= link_to('Sign in', new_user_session_path)  %>  
                              </li>
                              <li>
                                <%= link_to('Sign up', new_user_registration_path)  %>
                              </li>
                            <% end %>
                          <% if current_user && current_user.admin? %>
                               <li>
                             <%= link_to('page admin', adminpage_index_path)  %>
                                </li>
                                <% end %>
                         
                         
                        </ul>
                    </div>
                    <!-- Nav End -->
                </div>
            </nav>

            <!-- Header Meta Data -->
            <div class="header-meta d-flex clearfix justify-content-end">
                <!-- Favourite Area -->
                
                <!-- User Login Info -->
                <div class="user-login-info">
                    
                    <% if user_signed_in? %>

                   <%= link_to image_tag('core-img/user.svg'), user_path(current_user.id) %>

                   <% end %>
                </div>


                <!-- Cart Area -->
              
                <% if current_user %>
                <div class="cart-area">
                    <a href="#" id="essenceCartBtn"><%= image_tag("core-img/bag.svg", alt: "basket") %><span><%= total_quantity %></span></a>
                </div>
                <% end %>
                
            </div>

        </div>
    </header>
    <!-- ##### Header Area End ##### -->

app/views/shared/_index_items.html.erb
<!-- ##### Breadcumb Area Start ##### -->
<div class="breadcumb_area bg-img nyan">
    <div class="container h-100">
        <div class="row h-100 align-items-center">
            <div class="col-12">
                <h2>Shop</h2>
            </div>
        </div>
    </div>
</div>
<!-- ##### Breadcumb Area End ##### -->

<!-- ##### Shop Grid Area Start ##### -->
<section class="shop_grid_area section-padding-80">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-4 col-lg-3">
                <div class="shop_sidebar_area">

                    <!-- ##### Single Widget ##### -->
                    <div class="widget catagory mb-50">
                        <!-- Widget Title -->
                        <h6 class="widget-title mb-30">Catégories</h6>

                        <!--  Catagories  -->
                        <div class="catagories-menu">
                            <ul id="menu-content2" class="menu-content collapse show">
                                <!-- Single Item -->
                                <li data-toggle="collapse" data-target="#clothing">
                                  <%= link_to "Persan", show_category_path(id: 1) %>
                                </li>
                                <!-- Single Item -->
                                <li data-toggle="collapse" data-target="#shoes" class="collapsed">
                                    <%= link_to "Siamois", show_category_path(id: 2) %>
                                </li>
                                <!-- Single Item -->
                                <li data-toggle="collapse" data-target="#accessories" class="collapsed">
                                <%= link_to "Benghal", show_category_path(id: 3) %>
                                </li>
                                <!-- Single Item -->
                                <li data-toggle="collapse" data-target="#accessories" class="collapsed">
                                <%= link_to "New collection", show_category_path(id: 4) %>
                                </li>
                            </ul>
                        </div>
                    </div>
                    
                </div>
            </div>

            <div class="col-12 col-md-8 col-lg-9">
                <div class="shop_grid_product_area">
                    <div class="row">
                        <div class="col-12">
                            <div class="product-topbar d-flex align-items-center justify-content-between">
                                <!-- Total Products -->
                                <div class="total-products">
                                    <p><span><%= @items.count %></span> products found</p>
                                </div>
                                <!-- Sorting -->
                                <div class="product-sorting d-flex">
                                    <p>Sort by:</p>
                                    <form action="#" method="get">
                                        <select name="select" id="sortByselect">
                                            <option value="value">Highest Rated</option>
                                            <option value="value">Newest</option>
                                            <option value="value">Price: $$ - $</option>
                                            <option value="value">Price: $ - $$</option>
                                        </select>
                                        <input type="submit" class="d-none" value="">
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">



                        <!-- Single Product -->
                        <% @items.each do |item| %>
                        <div class="col-12 col-sm-6 col-lg-4">
                            
                            <div class="single-product-wrapper">
                                <!-- Product Image -->
                                <div class="product-img">
                                   <% unless item.image.attachment.nil? %>
                                   <%= image_tag item.image %>
                                   <% else %>
                                   <img src="<%= item.image_url %>" alt="img shop">
                                   <!-- Favourite -->
                                   <div class="product-favourite">
                                       <a href="#" class="favme fa fa-heart"></a>
                                   </div>
                                   <% end %>
                                </div>
                                

                                <!-- Product Description -->
                                <div class="product-description">
                                    

                                       
                                        <h6><%= link_to item.title, item_path(item.id) %></h6>
                                   
                                    <p class="product-price"><%=number_to_currency( item.price, :unit=>'€') %></p>

                                    <!-- Hover Content -->
                                    <% if user_signed_in? %>
                                    <div class="hover-content">
                                        <!-- Add to Cart -->
                                        <div class="add-to-cart-btn">                                                  
                                             <%= link_to "Add to cart", cart_item_path(item_id: item.id), method: :post, class: "btn essence-btn" %>
                                        </div>
                                    </div>
                                    <% end %>

                                </div>

                            </div>
                            
                        </div>
                        <% end %>
                        <!-- Single Product -->

                    </div>
                </div>

                
            </div>
        </div>
    </div>
</section>